# Generated by Django 3.2 on 2023-11-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Quantity', models.FloatField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Date', models.DateField()),
                ('Employee_id', models.ForeignKey(db_column='Employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': 'ProductSale',
            },
        ),
    ]
