# Generated by Django 3.2 on 2023-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=255)),
                ('Position', models.CharField(max_length=255)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=19)),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
    ]
